CLASS zcl_jcrf_05_inherit_2_log_c460 DEFINITION INHERITING FROM zcl_jcrf_04_inherit_1_log_c460
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_jcrf_05_inherit_2_log_c460 IMPLEMENTATION.
ENDCLASS.
